sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=postman2case -m unittest discover
after_success:
  - pipenv run coveralls